name: Rust CI

on:
  push:
    branches:
      - dev
      - main

    tags:
      - "v*" # Trigger only when a tag starting with 'v' is pushed

  pull_request:

jobs:
  build:
    strategy:
      matrix:
        BUILD_TARGET: [debug, release]
        OS:
          - HOST: ubuntu-latest
          - HOST: windows-latest
          - HOST: macos-latest

    runs-on: ${{ matrix.OS.HOST }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.BUILD_TARGET }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET == 'debug' && 'dev' || matrix.BUILD_TARGET }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: derouter-${{ matrix.BUILD_TARGET }}-${{ matrix.OS.HOST }}
          path: target/${{ matrix.BUILD_TARGET }}/derouter${{ matrix.OS.HOST == 'windows-latest' && '.exe' || '' }}

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: derouter-release-*
          path: artifacts

      - name: Display structure of downloaded artifacts
        run: ls -R $GITHUB_WORKSPACE/artifacts

      - name: Rename artifacts
        run: |
          mv $GITHUB_WORKSPACE/artifacts/derouter-release-ubuntu-latest/derouter      $GITHUB_WORKSPACE/artifacts/derouter-release-linux-x86_64-${{ github.ref_name }}
          mv $GITHUB_WORKSPACE/artifacts/derouter-release-windows-latest/derouter.exe $GITHUB_WORKSPACE/artifacts/derouter-release-win32-x86_64-${{ github.ref_name }}.exe
          mv $GITHUB_WORKSPACE/artifacts/derouter-release-macos-latest/derouter       $GITHUB_WORKSPACE/artifacts/derouter-release-darwin-arm64-${{ github.ref_name }}

      - name: Draft release
        env:
          GH_TOKEN: ${{ github.token }}
        run: >
          gh release create ${{ github.ref_name }}
          -d
          --generate-notes
          $GITHUB_WORKSPACE/artifacts/derouter-release-linux-x86_64-${{ github.ref_name }}
          $GITHUB_WORKSPACE/artifacts/derouter-release-win32-x86_64-${{ github.ref_name }}.exe
          $GITHUB_WORKSPACE/artifacts/derouter-release-darwin-arm64-${{ github.ref_name }}
